name: Postman Collection Run

on:
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Postman Collection with Newman
        id: run-tests
        uses: gasparhe/newman-action@1.0.0
        with:
          collection: '37276248-99d2ac53-1e38-4202-a31d-10243ac48837'  # Postman Collection UID
          environment: '37276248-a955bc24-695e-4333-a396-79067ae4928f'  # Postman Environment Name
          apiKey: ${{ secrets.POSTMAN_API_KEY }}  # Use GitHub Secret
          envVar: SKIP_ENDPOINTS="GetById-Menus,Get statistics"

      - name: Send Failure Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          # Use connection URL for authentication
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          # Mail server settings for Outlook
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          # Email content
          subject: "Postman Collection Tests Failed"
          to: support@plusinnovations.co
          from: your_outlook_email@outlook.com
          body: |
            The Postman Collection tests have failed.
            Please check the workflow logs for more details.
