name: Postman Regression Test

on:
  workflow_dispatch:
env:
  REGRESSION_TEST_COLLECTION_UID: '37276248-99d2ac53-1e38-4202-a31d-10243ac48837'
  REGRESSION_ENVIRONMENT_UID: '37276248-a955bc24-695e-4333-a396-79067ae4928f'
  DEV_URL: 'https://aapli-dev-api.aapli.app/'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 60 seconds
        run: sleep 60

      - name: Checkout Code
        uses: actions/checkout@v2

      # ✅ Step 1: Check API Accessibility Before Running Tests
      - name: Check API Accessibility
        run: |
          echo "Checking API response..."
          curl -I https://aapli-dev-api.aapli.app/Cards/Add || exit 1

      # ✅ Step 2: Debug DNS Resolution
      - name: Debug DNS Resolution
        run: nslookup aapli-dev-api.aapli.app

      #
      - name: Run Regression Test Collection with Newman
        uses: gasparhe/newman-action@1.0.0
        with:
          collection: ${{env.REGRESSION_TEST_COLLECTION_UID }}  # Replace with Regression Test Collection UID
          environment: ${{ env.REGRESSION_ENVIRONMENT_UID }}  # Postman Environment Name
          apiKey: ${{ secrets.POSTMANSECRET }}  # Use GitHub Secret

      # ✅ Step 5: Send Email Notification on Failure
      - name: Send Failure Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          subject: "Postman Collection Tests Failed"
          to: support@plusinnovations.co
          from: your_outlook_email@outlook.com
          body: |
            The Postman Collection tests have failed.
            Please check the workflow logs for more details.
