name: Postman Regression Test

on:
  workflow_dispatch:

env:
  REGRESSION_TEST_COLLECTION_UID: '37276248-99d2ac53-1e38-4202-a31d-10243ac48837'
  REGRESSION_ENVIRONMENT_UID: '37276248-a955bc24-695e-4333-a396-79067ae4928f'
  DEV_URL: 'https://aapli-dev-api.aapli.app/'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:

      # ✅ Step 2: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # ✅ Step 4: Debug DNS Resolution (to check if domain resolves correctly)
      - name: Debug DNS Resolution
        run: nslookup aapli-dev-api.aapli.app
        continue-on-error: true

      # ✅ Step 5: Run Postman Regression Tests
      - name: Run Regression Test Collection with Newman
        uses: gasparhe/newman-action@1.0.0
        with:
          collection: ${{ env.REGRESSION_TEST_COLLECTION_UID }}  # Regression Test Collection UID
          environment: ${{ env.REGRESSION_ENVIRONMENT_UID }}  # Postman Environment UID
          apiKey: ${{ secrets.POSTMAN_API_KEY }}  # GitHub Secret for Postman API Key
          reporters: cli, json
          reporter-json-export: newman-report.json  # Save test report

      # ✅ Step 6: Send Email Notification on Failure
      - name: Send Failure Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          subject: "Postman Collection Tests Failed"
          to: support@plusinnovations.co
          from: your_outlook_email@outlook.com
          body: |
            The Postman Collection tests have failed.
            Please check the workflow logs for more details.
