name: Postman Collection Run

on:
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Postman Collection with Newman
        uses: gasparhe/newman-action@1.0.0
        with:
          collection: '37276248-fcc353f6-93a2-4be1-b60c-fbaa2ec72eae'  # Postman Collection UID
          environment: '37276248-6427117b-642d-4fcf-a80e-f72f735789a7'  # Postman Environment Name
          apiKey: ${{ secrets.POSTMAN_API_KEY }}  # Use GitHub Secret
